name: Build Wheels

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64
            platform: linux
          # Linux aarch64
          - os: ubuntu-latest
            target: aarch64
            platform: linux
          # macOS x86_64
          - os: macos-13
            target: x86_64
            platform: darwin
          # macOS aarch64 (Apple Silicon)
          - os: macos-14
            target: aarch64
            platform: darwin
          # Windows x86_64
          - os: windows-latest
            target: x86_64
            platform: windows

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'linux' && matrix.target == 'x86_64' && 'x86_64-unknown-linux-gnu' || matrix.platform == 'linux' && matrix.target == 'aarch64' && 'aarch64-unknown-linux-gnu' || matrix.platform == 'darwin' && matrix.target == 'x86_64' && 'x86_64-apple-darwin' || matrix.platform == 'darwin' && matrix.target == 'aarch64' && 'aarch64-apple-darwin' || matrix.platform == 'windows' && 'x86_64-pc-windows-msvc' || '' }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-${{ matrix.platform }}-${{ matrix.target }}"

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install maturin
        run: uv tool install maturin

      - name: Set up QEMU (for Linux aarch64)
        if: matrix.platform == 'linux' && matrix.target == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build wheels
        run: |
          uvx maturin build --release --out dist --find-interpreter ${{ matrix.platform == 'linux' && matrix.target == 'aarch64' && '--target aarch64-unknown-linux-gnu' || matrix.platform == 'linux' && matrix.target == 'x86_64' && '--target x86_64-unknown-linux-gnu' || '' }}

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform }}-${{ matrix.target }}
          path: dist/*.whl
          if-no-files-found: error

      - name: Upload wheels to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install maturin
        run: uv tool install maturin

      - name: Build sdist
        run: uvx maturin sdist --out dist

      - name: Upload sdist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: error

      - name: Upload sdist to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
